import Image from "next/image";
import Link from "next/link";
import { prisma } from "@/lib/prisma";

export default async function HomePage() {
  const [categories, products] = await Promise.all([
    prisma.category.findMany({ orderBy: { name: "asc" }, take: 8 }),
    prisma.product.findMany({ where: { isActive: true, isFeatured: true }, include: { images: { where: { isMain: true }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 8 }),
  ]);
  return <div className="flex flex-col gap-16 pb-16"><section className="relative h-[70vh] min-h-[520px] flex items-center justify-center overflow-hidden"><div className="absolute inset-0 bg-zinc-900"><Image src="https://images.unsplash.com/photo-1617038220319-276d3cfab638?q=80&w=2070&auto=format&fit=crop" alt="Joias elegantes" fill className="object-cover opacity-70" priority /></div><div className="relative z-10 text-center text-white px-4"><p className="text-sm uppercase tracking-[0.3em] mb-4">RG Acessórios</p><h1 className="text-5xl md:text-7xl font-light mb-6">A beleza está nos detalhes</h1><Link href="/buscar" className="inline-flex bg-white text-zinc-900 px-8 py-3 rounded">Explorar peças</Link></div></section><section className="container mx-auto px-4"><h2 className="text-2xl font-light text-center mb-8 uppercase tracking-wider">Categorias</h2><div className="flex flex-wrap justify-center gap-3">{categories.map((category) => <Link key={category.id} href={`/categoria/${category.slug}`} className="border border-zinc-200 px-5 py-3 rounded hover:border-rose-400 hover:text-rose-500 transition-colors">{category.name}</Link>)}</div></section><section className="container mx-auto px-4"><div className="flex justify-between items-end mb-8"><h2 className="text-2xl font-light uppercase tracking-wider">Destaques</h2><Link href="/buscar" className="text-sm text-rose-500">Ver catálogo</Link></div>{products.length === 0 ? <p className="text-zinc-500">Em breve, novas peças em destaque.</p> : <div className="grid grid-cols-2 md:grid-cols-4 gap-6">{products.map((product) => <Link href={`/produto/${product.slug}`} key={product.id} className="group"><div className="relative aspect-[3/4] bg-zinc-100 rounded-xl overflow-hidden">{product.images[0] && <Image src={product.images[0].url} alt={product.name} fill className="object-cover group-hover:scale-105 transition-transform" />}</div><h3 className="mt-3 text-sm font-medium">{product.name}</h3><p className="mt-1 font-semibold">R$ {Number(product.price).toFixed(2).replace(".", ",")}</p></Link>)}</div>}</section></div>;
}
